### ISSUE TITLE
lxqt-archiver fails to build with new glib2 2.61.2

### ISSUE THREAD

**Issue by david-geiger** [lxqt/lxqt-archiver#113]
hi,

I tried on Mageia Cauldron (linux) to build lxqt-archiver 0.0.96 but it fails to build with recent glib2 2.61.2:

> In file included from /home/pterjan/rpmbuild/BUILD/lxqt-archiver-0.0.96/src/core/fr-command-ace.c:31:
/home/pterjan/rpmbuild/BUILD/lxqt-archiver-0.0.96/src/core/glib-utils.h:69:21: error: conflicting types for 'g_ptr_array_copy'
 GPtrArray *         g_ptr_array_copy             (GPtrArray   *array);
                     ^~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:31,
                 from /home/pterjan/rpmbuild/BUILD/lxqt-archiver-0.0.96/src/core/fr-command-ace.c:27:
/usr/include/glib-2.0/glib/garray.h:141:12: note: previous declaration of 'g_ptr_array_copy' was here
 GPtrArray *g_ptr_array_copy               (GPtrArray        *array,
            ^~~~~~~~~~~~~~~~
make[2]: *** [src/core/CMakeFiles/lxqt-archiver-core.dir/build.make:144: src/core/CMakeFiles/lxqt-archiver-core.dir/fr-command-ace.c.o] Error 1
make[2]: Leaving directory '/home/pterjan/rpmbuild/BUILD/lxqt-archiver-0.0.96/build'
make[2]: *** Waiting for unfinished jobs....

[build.0.20190812145901.log](https://github.com/lxqt/lxqt-archiver/files/3534227/build.0.20190812145901.log)

Regards,
David

**Comment by tsujan** [comment]
Thanks!

glib2 2.61.2 has added the function `GPtrArray *g_ptr_array_copy (GPtrArray *array, GCopyFunc func, gpointer user_data)`, which is in conflict with ours. This part of the code is taken from engrampa. However, `g_ptr_array_copy` isn't used anywhere.

I don't have glib2 2.61.2 yet. Could you please comment out the function `g_ptr_array_copy` in `src/core/glib-utils.h` and `src/core/glib-utils.c` to see if the compilation can be done with that version of glib? If there's still another conflict, please add the messages!

**Comment by tsujan** [comment]
BTW, only the latest git lxqt-archiver is ready for use.

**Comment by david-geiger** [comment]
Using the latest git snapshot and commented out the function g_ptr_array_copy it still fails to build:

> /home/iurt/rpmbuild/BUILD/lxqt-archiver-0.0.96/src/core/glib-utils.c: In function 'g_utf8_strchug':
/home/iurt/rpmbuild/BUILD/lxqt-archiver-0.0.96/src/core/glib-utils.c:285:13: warning: memmove
  285 |  g_memmove (string, scan, strlen (scan) + 1);
      |             ^~~~~~~~~
/home/iurt/rpmbuild/BUILD/lxqt-archiver-0.0.96/src/core/glib-utils.c: At top level:
/home/iurt/rpmbuild/BUILD/lxqt-archiver-0.0.96/src/core/glib-utils.c:573:1: error: expected identifier or '(' before '{' token
  573 | {
      | ^
make[2]: *** [src/core/CMakeFiles/lxqt-archiver-core.dir/build.make:482: src/core/CMakeFiles/lxqt-archiver-core.dir/glib-utils.c.o] Error 1
make[2]: Leaving directory '/home/iurt/rpmbuild/BUILD/lxqt-archiver-0.0.96/build'
make[2]: *** Waiting for unfinished jobs....

**Comment by tsujan** [comment]
> it still fails to build:

I'm afraid this is about a mistake you made while commenting out `g_ptr_array_copy`.

**Comment by david-geiger** [comment]
Should I comment from line 571 to line 584? in src/core/glib-utils.c file

**Comment by tsujan** [comment]
> Should I comment from line 571 to line 584? in src/core/glib-utils.c file

Exactly!

I'm making a patch to comment out all unused C functions in utils files. As far as I checked the source of the latest GLib, only `g_ptr_array_copy` was used as the name of a new function. So, the problem should be solved.

**Comment by tsujan** [comment]
You could use/test this branch: https://github.com/lxqt/lxqt-archiver/tree/redundant_funct

**Comment by david-geiger** [comment]
So now I get (using Qt 5.13.0):

> In file included from /usr/include/libfm-qt/core/folder.h:35,
                 from /usr/include/libfm-qt/foldermodelitem.h:30,
                 from /usr/include/libfm-qt/foldermodel.h:33,
                 from /usr/include/libfm-qt/folderview.h:29,
                 from /usr/include/libfm-qt/filedialog.h:15,
                 from /home/iurt/rpmbuild/BUILD/lxqt-archiver-0.0.96/src/extractfiledialog.h:4,
                 from /home/iurt/rpmbuild/BUILD/lxqt-archiver-0.0.96/src/extractfiledialog.cpp:1:
/usr/include/libfm-qt/core/gioptrs.h: In member function 'QString Fm::GErrorPtr::message() const':
/usr/include/libfm-qt/core/gioptrs.h:75:26: error: 'QString::QString(const char*)' is private within this context
   75 |             return err_->message;
      |                          ^~~~~~~
In file included from /usr/include/qt5/QtCore/qhashfunctions.h:44,
                 from /usr/include/qt5/QtCore/qlist.h:47,
                 from /usr/include/qt5/QtCore/qhash.h:46,
                 from /usr/include/qt5/QtCore/qdebug.h:45,
                 from /usr/include/qt5/QtCore/QDebug:1,
                 from /usr/include/libfm-qt/core/gobjectptr.h:8,
                 from /usr/include/libfm-qt/core/filepath.h:5,
                 from /usr/include/libfm-qt/filedialog.h:5,
                 from /home/iurt/rpmbuild/BUILD/lxqt-archiver-0.0.96/src/extractfiledialog.h:4,
                 from /home/iurt/rpmbuild/BUILD/lxqt-archiver-0.0.96/src/extractfiledialog.cpp:1:
/usr/include/qt5/QtCore/qstring.h:835:5: note: declared private here
  835 |     QString(const char *ch);
      |     ^~~~~~~
In file included from /home/iurt/rpmbuild/BUILD/lxqt-archiver-0.0.96/src/extractfiledialog.h:4,
                 from /home/iurt/rpmbuild/BUILD/lxqt-archiver-0.0.96/src/extractfiledialog.cpp:1:
/usr/include/libfm-qt/filedialog.h: In member function 'void Fm::FileDialog::setDefaultSuffix(const QString&)':
/usr/include/libfm-qt/filedialog.h:104:46: error: 'QChar::QChar(char)' is private within this context
  104 |         if(!suffix.isEmpty() && suffix[0] == '.') {
      |                                              ^~~
In file included from /usr/include/qt5/QtCore/qhash.h:44,
                 from /usr/include/qt5/QtCore/qdebug.h:45,
                 from /usr/include/qt5/QtCore/QDebug:1,
                 from /usr/include/libfm-qt/core/gobjectptr.h:8,
                 from /usr/include/libfm-qt/core/filepath.h:5,
                 from /usr/include/libfm-qt/filedialog.h:5,
                 from /home/iurt/rpmbuild/BUILD/lxqt-archiver-0.0.96/src/extractfiledialog.h:4,
                 from /home/iurt/rpmbuild/BUILD/lxqt-archiver-0.0.96/src/extractfiledialog.cpp:1:
/usr/include/qt5/QtCore/qchar.h:589:5: note: declared private here
  589 |     QChar(char c) Q_DECL_NOTHROW;
      |     ^~~~~
make[2]: *** [src/CMakeFiles/lxqt-archiver.dir/build.make:281: src/CMakeFiles/lxqt-archiver.dir/extractfiledialog.cpp.o] Error 1
make[2]: Leaving directory '/home/iurt/rpmbuild/BUILD/lxqt-archiver-0.0.96/build'
make[2]: *** Waiting for unfinished jobs....

**Comment by tsujan** [comment]
You may not have the latest git libfm-qt. It compiles fine with Qt 5.13, which I have here.

**Comment by david-geiger** [comment]
So ok now it compiles fine!

**Comment by tsujan** [comment]
> So ok now it compiles fine!

Thanks for testing!

**Comment by stefonarch** [comment]
Same here, compiles only redundant-branch.

**Comment by tsujan** [comment]
> Same here, compiles only redundant-branch.

The fix was here: https://github.com/lxqt/lxqt-archiver/pull/114. I merged it right now.
